### ISSUE TITLE
[cetriolo-back] implementar envio de usuario no request, para armazenamento no BD DW

### ISSUE THREAD

**Issue by oliveiramclaraa** [DataWatchOrg/cetriolo-back#7]

**Comment by oliveiramclaraa** [comment]
req.getUserPrincipal().getName() implementado no filter

**Comment by RoneFB** [comment]
Gasto 1:30m

**Comment by RoneFB** [comment]
Gasto 1:30m anteriormente + 1hr Devido a implementação do Filter afim de ignorar a chamada para rota /login
total: 2:30m
